
export const storyActions = {
    SET_STORY: 'SET_STORY',
    SET_STORIES: 'SET_STORIES',
    ADD_STORY: 'ADD_STORY',
    UPDATE_STORY: 'UPDATE_STORY',
    REMOVE_STORY: 'REMOVE_STORY',
    SET_IS_LOADING: 'SET_IS_LOADING'
}